services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules

volumes:
  frontend_node_modules:
